### ISSUE TITLE
Add a `--no-color` CLI argument

### ISSUE THREAD

**Issue by davidjeddy** [tgenv/tgenv#22]
When running tgenv in CI/CD pipelines the output is polluted with the color characters.

```
[2023-03-09T12:20:42.216Z] [0;32m[INFO] Installation of terragrunt v0.43.2 successful[0;39m
[2023-03-09T12:20:42.538Z] [0;32m[INFO] Switching to v0.43.2[0;39m
[2023-03-09T12:20:43.707Z] [0;32m[INFO] Switching completed[0;39m
[2023-03-09T12:20:44.438Z] [0;32m[INFO] Switching to v0.43.2[0;39m
[2023-03-09T12:20:45.159Z] [0;32m[INFO] Switching completed[0;39m
```

Having the ability for tgenv to not output the color codes would be a great feature add.

**Comment by iokiwi** [comment]
@davidjeddy out of interest, which CI/CD are you using? I use it in gitlab and the colors work fine.

I can see some merit to this request though. terraform and terragrunt both have a `-no-color` option

e.g 

```bash
$ terragrunt plan --help | grep -no-color
  -no-color           If specified, output won't contain any color.
```

Since tgenv wraps the terragrunt bin with our own script we should be able to check if the -no-color argument has been specified and disable color in tgenv output as well.

For this I would recommend refactoring colored output into an extracted function and having that function check for a no color flag.

Cant promise when I will get onto pull request for it but feel free to raise one and I will promise to be responsive to reviewing.

Will tag as good first issue.

**Comment by davidjeddy** [comment]
We use Jenkins to execute our pipelines.

**Comment by iokiwi** [comment]
Sorry this year has been... challenging. Finally got onto this. Pull request here: #29

**Comment by davidjeddy** [comment]
Thank you @iokiwi; awesome you found time to address this. I will push the update to my teams today!
